# 注意请保存为UTF-8的格式
spring: 
  profiles: 
    active: - dev
    
---
spring: 
  profiles: dev     # 开发环境
    application: 
      name: microservicecloud-config-oxygen-dev
    
---
spring: 
  profiles: test    # 测试环境
    application: 
      name: microservicecloud-config-oxygen-test



